defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.11.3-stretch-browsers

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
      - run:
          name: Run tslint
          command: npm run tslint
      - run:
          name: Run tests
          command: npm test
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "64:92:9e:ad:f1:89:de:37:0e:20:a9:c5:1e:a2:a6:6b"
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: ~/repo/.circleci/publish-and-tagging.sh

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
