version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # TODO: add test
      # - run:
      #     name: test
      #     command: npm test
workflows:
  version: 2
  per-commit:
    jobs:
      - build
      - publish:
          requires:
            - build
          context: org-global
          filters:
            branches:
              only: master
